apiVersion: v1
kind: Namespace
metadata:
  name: ceph-block-storage

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-block-provisioner-service-account
  namespace: ceph-block-storage

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ceph-block-provisioner-role
  namespace: ceph-block-storage
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ceph-block-provisioner-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "persistentvolumeclaims", "configmaps", "pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ceph-block-provisioner-bind
  namespace: ceph-block-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-block-provisioner-role
subjects:
  - kind: ServiceAccount
    name: ceph-block-provisioner-service-account
    namespace: ceph-block-storage

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ceph-block-provisioner-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ceph-block-provisioner-role
subjects:
  - kind: ServiceAccount
    name: ceph-block-provisioner-service-account
    namespace: ceph-block-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-block-provisioner
  namespace: ceph-block-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph-block-provisioner
  template:
    metadata:
      labels:
        app: ceph-block-provisioner
    spec:
      serviceAccountName: ceph-block-provisioner-service-account
      containers:
        - name: ceph-block-provisioner
          image: rancher/ceph-block-provisioner:v0.0.30
          imagePullPolicy: IfNotPresent
          command:
            - ceph-block-provisioner
            - --debug
            - start
            - --config
            - /etc/config/config.json
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_MOUNT_PATH
              value: /etc/config/
      volumes:
        - name: config-volume
          configMap:
            name: ceph-block-config

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-block
provisioner: rancher.io/ceph-block
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: local-storage
    objectset.rio.cattle.io/owner-namespace: kube-system
  name: ceph-block-config
  namespace: ceph-block-storage
data:
  config.json: |-
    {
        "nodePathMap": [
                {
                        "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths": [
                                "/opt/ceph-block-provisioner"
                        ]
                },
                {
                        "node": "bradley",
                        "paths": [
                                "/opt/ceph-block-provisioner"
                        ]
                },
                {
                        "node": "scremlin",
                        "paths": [
                                "/mnt/raid1"
                        ]
                }
        ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent
