replicaCount: 1

service:
  type: LoadBalancer
  port: 8080
  protocol: TCP
  name: http

prometheus:
  enabled: true
  serviceName: "thanos-app-query-frontend"
  serviceNamesapce: "default"

  tls:
    enabled: false
    secretName: "tls-kubevirt-manager"
